[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "http://localhost:3000/*"
  to = "https://eisvil.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "https://--eisvil.netlify.app/*"
  to = "https://eisvil.netlify.app/:splat"
  status = 200

